import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import type { Metadata } from 'next';
import { DM_Sans, IBM_Plex_Mono, Lora } from 'next/font/google';
import './globals.css';

const fontSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontSerif = Lora({
  subsets: ['latin'],
  variable: '--font-serif',
});
const fontMono = IBM_Plex_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <Header />
        <main className="flex-1 items-stretch flex bg-white/30">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
